### ISSUE TITLE
Error IsDirectoryError when Preproccess input data

### ISSUE THREAD

**Issue by kobrafarshidi** [SatyamGaba/vqa#1]
HI @SatyamGaba 
I do all step by step but
when running  python3 make_vacabs_for_questions_answers.py --input_dir='../COCO-2015'
I see some error could you help me please

ubuntu@ubuntu-VirtualBox:~/visual_question_answering/utilities$ python3 make_vacabs_for_questions_answers.py --input_dir='../COCO-2015'
Traceback (most recent call last):
  File "/home/ubuntu/visual_question_answering/utilities/make_vacabs_for_questions_answers.py", line 79, in <module>
	main(args)
  File "/home/ubuntu/visual_question_answering/utilities/make_vacabs_for_questions_answers.py", line 68, in main
	make_vocab_questions(input_dir+'/Questions')
  File "/home/ubuntu/visual_question_answering/utilities/make_vacabs_for_questions_answers.py", line 14, in make_vocab_questions
	datasets = os.listdir(input_dir)
FileNotFoundError: [Errno 2] No such file or directory: '../COCO-2015/Questions'

**Comment by SatyamGaba** [comment]
Hi,

You have to add questions and their answers in the directory as given in the README file. It will be used to train the VQA Model. 
For this repository, COCO dataset has been used.

**Comment by kobrafarshidi** [comment]
Hi,At first many thanks for your email but I did all this readme file just step by step .I send you images to show you that I had added all files to project before I run it but it could not work.Thank you for guide me
    On Monday, July 18, 2022 at 12:22:52 PM GMT+4:30, Satyam Gaba ***@***.***> wrote:  
 
 


Hi,

You have to add questions and their answers in the directory as given in the README file. It will be used to train the VQA Model.
For this repository, COCO dataset has been used.
